version: '3'

vars:
  BinName: templet
  SrcMain: ./cmd/cli/main.go
  DistDir: ./dist

tasks:
  audit:
    desc: 'Realiza comprobaciones de control de calidad en el código fuente'
    cmds:
      - go vet ./...
      - go test ./...
      - go mod verify
      - go mod tidy
  build:
    desc: 'Genera el binario ejecutable basándose en la configuración del sistema operativo'
    vars:
      Version:
        sh: "git describe --tags --abbrev=0"
    cmds:
      - mkdir -p ./dist
      - rm -rf ./dist/{{.GOOS}}-{{.GOARCH}}/*
      - |
        CGO_ENABLED=0 GOOS={{.GOOS}} GOARCH={{.GOARCH}} go build \
          -o ./dist/{{.GOOS}}-{{.GOARCH}}/{{.BinName}}{{.Ext}} \
          -ldflags "-s -w -X main.Version={{.Version}}" \
          {{.SrcMain}}
  build-linux:
    desc: "Genera el binario ejecutable para Linux"
    deps: [audit]
    cmds:
      - task: build
        vars: {GOOS: linux, GOARCH: amd64, Ext: ""}
  build-windows:
    desc: "Genera el binario ejecutable para Windows"
    deps: [audit]
    cmds:
      - task: build
        vars: {GOOS: windows, GOARCH: amd64, Ext: ".exe"}
