version: '3'

vars:
  BinName: tpl
  SrcMain: ./cmd/cli/main.go
  BuildTime: '{{now | date "2006-01-02T15:04:05"}}'
  DistDir: ./dist
  CommitHash:
    sh: "git rev-parse --short HEAD"
  Version:
    sh: "git describe --tags --abbrev=0"

tasks:
  default:
    desc: 'Muestra las tareas disponibles (task -l)'
    cmds:
      - task --list
  clean:
    desc: "Limpia archivos generados en la compilación"
    cmds:
    - rm -rf {{.DistDir}}/*
    - rm -rf /tmp/templet-*
  fmt:
    # Instalarlo a través del comando `go install github.com/segmentio/golines@latest
    desc: 'Formatea el código fuente a traves del programa `golines'
    cmds:
      - golines -m 130 --base-formatter="gofmt" -w .
  audit:
    desc: 'Realiza comprobaciones de control de calidad en el código fuente'
    # Habilitar si golines está instalado
    # deps: [fmt]
    cmds:
      - go vet ./...
      - go test ./...
      - go mod verify
  build:
    desc: 'Genera el binario ejecutable basándose en la configuración del sistema operativo'
    cmds:
      - mkdir -p ./dist
      - |
        CGO_ENABLED=0 GOOS={{.GOOS}} GOARCH={{.GOARCH}} go build \
          -o ./dist/{{.GOOS}}-{{.GOARCH}}/{{.BinName}}{{.Ext}} \
          -ldflags "-s -w -X main.Version={{.Version}}" \
          {{.SrcMain}}
  build-linux:
    desc: "Genera el binario ejecutable para Linux"
    deps: [clean, audit]
    cmds:
      - task: build
        vars: {GOOS: linux, GOARCH: amd64, Ext: ""}
  build-windows:
    desc: "Genera el binario ejecutable para Windows"
    deps: [clean, audit]
    cmds:
      - task: build
        vars: {GOOS: windows, GOARCH: amd64, Ext: ".exe"}
  run:
    desc: "Ejecuta el programa a traves del comando `go run {{.SrcMain}}`"
    cmds:
      - go run {{.SrcMain}} -n /tmp/prueba  file:/home/walter/Desarrollo/go/templet/sample/clthexa
